INSERT INTO location (id, district) values ('1','Distric 1');
INSERT INTO location (id, district) values ('2','Distric 2');
INSERT INTO location (id, district) values ('3','Distric 3');
INSERT INTO location (id, district) values ('4','Distric 4');
INSERT INTO location (id, district) values ('5','Distric 5');
INSERT INTO location (id, district) values ('6','Distric 6');
INSERT INTO location (id, district) values ('7','Distric 7');
INSERT INTO location (id, district) values ('8','Distric 8');
INSERT INTO location (id, district) values ('9','Distric 9');
INSERT INTO location (id, district) values ('10','Distric 10');
INSERT INTO location (id, district) values ('11','Distric 11');
INSERT INTO location (id, district) values ('12','Distric 12');
INSERT INTO location (id, district) values ('13','Binh Thanh District');
INSERT INTO location (id, district) values ('14','Go Vap District');
INSERT INTO location (id, district) values ('15','Thu Duc Distric');
INSERT INTO location (id, district) values ('16','Phu Nhuan District');
INSERT INTO location (id, district) values ('17','Tan Binh District');
INSERT INTO location (id, district) values ('18','Tan Phu District');
INSERT INTO location (id, district) values ('19','Binh Tan District');